FROM postgis/postgis:15-3.5

# Instala plperlu
RUN apt-get update && apt-get install -y \
    postgresql-plperl-15 \
    && rm -rf /var/lib/apt/lists/*

USER root

RUN mkdir -p /pg-index/15-5432 \
    && chown postgres:postgres /pg-index/15-5432

RUN mkdir -p /pg-unlogged/15-5432 \
    && chown postgres:postgres /pg-unlogged/15-5432

RUN mkdir -p /mnt/apagarvolume \
    && chown postgres:postgres /mnt/apagarvolume \

