name: Build DB Image (PG15 Alpine + PL/Perl)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/pg15-alpine-plperl:latest
          docker build -f Dockerfile.pg15-alpine-plperl -t "$IMAGE" .
          docker push "$IMAGE"
